/* Users constants */
module.exports = {
  // LOGIN ACTIONS
  'LOGIN_REQUEST': 'LOGIN_REQUEST',
  'LOGIN_SUCCESS': 'LOGIN_SUCCESS',
  'LOGIN_FAILURE': 'LOGIN_FAILURE',
  // SIGN UP ACTIONS
  'SIGNUP_REQUEST': 'SIGNUP_REQUEST',
  'SIGNUP_SUCCESS': 'SIGNUP_SUCCESS',
  'SIGNUP_FAILURE': 'SIGNUP_FAILURE',
  // EVENTS ACTIONS
  'EVENT_REQUEST': 'EVENT_REQUEST',
  'EVENT_SUCCESS': 'EVENT_SUCCESS',
  'EVENT_FAILURE': 'EVENT_FAILURE',
  // TOKEN EXPIRED
  'TOKEN_EXPIRED': 'TOKEN_EXPIRED'
}
